### ISSUE TITLE
Inconsistent typing of decoded JSON values

### ISSUE THREAD

**Issue by nospampleasemam** [stig/json-framework#191]
It seems that when a JSON value is numerical, SBJson returns either an `__NSCFNumber` or an `__NSCFString`, depending on size. As I was originally working with small numbers only, I was receiving an `__NSCFNumber` and calling `[obj stringValue]`. When larger inputs were introduced, I saw an `NSInvalidArgumentException` crash. It took me some time to track this issue down; I haven't written a standalone test case yet, but I will work on one tonight. This error could potentially open a denial of service vulnerability for systems in production.

Thanks for the library, and my apologies if I'm mistaken in anything I've said :-)

**Comment by stig** [comment]
Cannot reproduce.
