### ISSUE TITLE
Where to download old version?

### ISSUE THREAD

**Issue by bagusflyer** [stig/json-framework#199]
I have a project using SBJson but it's using old version which doesn't support ARC. I want to upgrade my project to support ARC. But I don't want to use the version 4.0 and above because the interface is changed and I have too much work to do. Can you tell me which version (should be version 3.x) is the first version supports ARC and where to download it? Thanks

**Comment by stig** [comment]
Hello, and thanks for using sbjson!

3.1 is the first version to support ARC. I would recommend using 3.2 though, as it had an important bug fix for big numbers. (This is documented in the NEWS.md in the source, by the way.)

The recommended way to get the code is to use CocoaPods, but you can also just download the source from GitHub. Look under the “releases” tab. (I can't give a link as I am on a mobile at the moment.)

Stig
