### ISSUE TITLE
Carthage compatibility

### ISSUE THREAD

**Issue by robb** [stig/json-framework#202]
Would you be interested in a Pull Request that added a Framework target for iOS and made sure that SBJSON was building nicely with [Carthage](https://github.com/Carthage/Carthage)?

This wouldn't negatively affect the CocoaPods integration, which seems to be the currently recommended way of doing things.

**Comment by stig** [comment]
I'd prefer not adding more targets if possible, as it adds another dimension to tests. Is there a reason the existing SBJson or sbjson-ios targets won't work for this?

**Comment by robb** [comment]
Carthage builds frameworks exclusively.

**Comment by stig** [comment]
Sorry, you're going to have to be a bit more specific :-)

**Comment by robb** [comment]
Sorry!

SBJSON currently has two targets, `SBJson.framework` for Mac and `SBJson-ios.a` for iOS.

Carthage's approach to dependency management uses `xcodebuild` to produce all artifacts. It builds [shared schemes for dynamic frameworks](https://github.com/carthage/carthage#supporting-carthage-for-your-framework), which can be used on any version of OS X, but only on iOS 8 or later.
[Heres a talk on the subject by one of its creators](https://realm.io/news/swift-dependency-management-with-carthage/).

From what I can tell, the Mac framework already builds fine with Carthage :sparkles:, but the static library is not picked up.

**Comment by stig** [comment]
I'm certainly open for pull requests that makes Carthage pick up the static target too, if it still works for CocoaPods! If that isn't possible, I will entertain the idea of another target.

**Comment by stig** [comment]
This was added in #216
