### ISSUE TITLE
SBJson 3.2 is missing in cocoapods 

### ISSUE THREAD

**Issue by andreyslyusar** [stig/json-framework#210]
SBJson and SBJson4 have 4.0.2 version in cocoapods repo. Why 3.2 compatibility was dropped?

**Comment by stig** [comment]
> On 1 Sep 2015, at 14:13, Andrey Slyusar <notifications@github.com> wrote:
> 
> SBJson and SBJson4 have 4.0.2 version in cocoapods repo. Why 3.2 compatibility was dropped?
> 
Version 4 and above has an incompatible interface with version <4. However, version 3.x and version 4.x are compatible in that both can be installed in the same applications. (I renamed all the classes to include the digit “4” for this purpose.) Further, you can install both from cocoa pods. See the spec directory here: https://github.com/CocoaPods/Specs/tree/master/Specs/SBJson <https://github.com/CocoaPods/Specs/tree/master/Specs/SBJson>

Does this answer your question?

Stig

**Comment by andreyslyusar** [comment]
Hi Stig,

I think yes. I was just confuse as I did not find this information in change log. I will try to use 4.x cocoapods version.

**Comment by stig** [comment]
It's in the change log for [version 4.0.0a3](https://github.com/stig/json-framework/blob/master/NEWS.md#400-alpha3-november-17th-2013), but perhaps not as prominent as it should be :-)

**Comment by andreyslyusar** [comment]
Hi Stig. 

The problem was in pod file: s.dependency 'SBJson', ' ~> 3.2' will install 4.0.2 version. I fix by setting explicit version for use s.dependency 'SBJson', '3.2'.

But in case you make update in cocoapods
![screenshot 2015-09-16 12 35 08](https://cloud.githubusercontent.com/assets/1401690/9902563/b5b9ed90-5c6f-11e5-8af0-27d651f5c1cc.png)

you should remove install warning: "[!] SBJson has been deprecated in favor of SBJson4"
