### ISSUE TITLE
New release Needed

### ISSUE THREAD

**Issue by amrutsabade** [stig/json-framework#256]
Hi ,
I have raised a PR (https://github.com/stig/json-framework/pull/253) for carthage support and its been merged into master.

Can you please release a new version from latest master so that we can use the fix 

Please let me know

Thanks & Regards
Amrut Sabade

**Comment by stig** [comment]
Hi @amrutsabade, will this do? https://github.com/stig/json-framework/releases/tag/v5.0.1

I assume Carthage doesn't care about me publishing to Cocoapods...

**Comment by amrutsabade** [comment]
Hi,
Yes thank you this should solve the problem for Carthage.

Thank you for your support.

Thanks & Regards
Amrut Sabade
