### ISSUE TITLE
You Rock

### ISSUE THREAD

**Issue by peterboni** [stig/json-framework#285]
Awesome library. Thank you @stig !

I'm working in Swift and thought I would help others in a similar boat with a few short example Gists:

1. [SBJsonChunkedParse](https://gist.github.com/peterboni/a8b858460c26ccd5a54643dbcda83726)
2. [SBJsonSelectiveChunkedParseFromStream](https://gist.github.com/peterboni/70820bb53c10f094396cdac8d8d0f6cc)
3. [SBJsonChunkedGenToFile](https://gist.github.com/peterboni/f019b34ed1065e1744483c33ffaf014d)

**Comment by stig** [comment]
Thank you very much! I'm glad you like it! :-)

**Comment by stig** [comment]
Those are cool examples. I am open to adding a contrib project showing how to use SBJson from Swift.

**Comment by peterboni** [comment]
If I get time I'll put one together. Just thought the quick (and dirty) playgrounds that I built to work out myself how to do what I needed to do in my side project may help others if they search through this repo Issues for "Swift" and "Example".
